[project]
name = "MGP-QDB"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "authlib>=1.5.2",
    "httpx>=0.28.1",
    "pydantic>=2.11.4",
    "streamlit>=1.45.0",
    "toml>=0.10.2",
]
